[package]
name = "RustAutoDevOps"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
axum = { version = "0.7", features = ["http1", "http2", "macros"] }
tokio = { version = "1.0", features = ["full"] }

# Middleware + Layers
tower = { version = "0.4", features = ["util", "timeout"] }
tower-http = { version = "0.5", features = ["cors", "trace", "compression-gzip"] }

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Environment and configuration
dotenv = "0.15"

# Utilities
uuid = { version = "1.0", features = ["v4", "serde"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# URL handling
url = "2.4"
urlencoding = "2.1"

# Date/time handling
chrono = { version = "0.4", features = ["serde"] }

# JWT handling
jsonwebtoken = "9.2"

# Password hashing
argon2 = "0.5"

# Async traits
async-trait = "0.1"

# Error handling
anyhow = "1.0"
thiserror = "1.0"
# Database
mongodb = "2.8"
tokio-stream = "0.1"
futures = "0.3"

# Time handling
time = { version = "0.3", features = ["macros", "serde"] }

# Additional axum features
axum-extra = { version = "0.9", features = ["cookie"] }