server:
  host: "0.0.0.0"
  port: 8000
  workers: null  # null means auto-detect
  max_connections: 1000
  request_timeout_seconds: 30
  graceful_shutdown_timeout_seconds: 30
  tls: null  # Optional TLS configuration

database:
  mongodb_uri: "mongodb://localhost:27017"
  database_name: "rustci"
  connection_pool_size: 10
  connection_timeout_seconds: 10
  query_timeout_seconds: 30
  retry_attempts: 3
  enable_ssl: false

security:
  jwt:
    secret: "your-super-secure-jwt-secret-key-here"
    expires_in_seconds: 3600
    refresh_expires_in_seconds: 86400
    issuer: "rustci"
    audience: "rustci-api"
    algorithm: "HS256"
  
  oauth:
    github:
      client_id: "your-github-oauth-client-id"
      client_secret: "your-github-oauth-client-secret"
      redirect_url: "http://localhost:8000/api/sessions/oauth/github/callback"
      scopes:
        - "user:email"
        - "repo"
  
  encryption:
    key: "base64-encoded-32-byte-encryption-key-here"
    algorithm: "AES-256-GCM"
  
  rate_limiting:
    requests_per_minute: 60
    burst_size: 10
    enable_per_user_limits: true
    whitelist_ips:
      - "127.0.0.1"
      - "::1"
  
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    allow_credentials: true
    max_age_seconds: 3600

observability:
  logging:
    level: "info"
    format: "json"  # "json" or "pretty"
    output: "stdout"  # "stdout", "stderr", or file path
    enable_file_rotation: false
    max_file_size_mb: 100
    max_files: 10
  
  metrics:
    enabled: true
    endpoint: "/metrics"
    collection_interval_seconds: 60
    export_timeout_seconds: 10
    custom_metrics: {}
  
  tracing:
    enabled: false
    endpoint: null
    service_name: "rustci"
    service_version: "0.1.0"
    sample_rate: 0.1
    export_timeout_seconds: 10

ci:
  max_concurrent_pipelines: 10
  pipeline_timeout_seconds: 3600
  workspace_cleanup_interval_seconds: 300
  default_executor: "docker"
  executors:
    docker:
      enabled: true
      max_concurrent_jobs: 5
      resource_limits:
        cpu_cores: 2.0
        memory_mb: 2048
        disk_mb: 10240
        network_bandwidth_mbps: null
      timeout_seconds: 1800
      retry_attempts: 2
      config: {}
    
    kubernetes:
      enabled: false
      max_concurrent_jobs: 10
      resource_limits:
        cpu_cores: 4.0
        memory_mb: 4096
        disk_mb: 20480
        network_bandwidth_mbps: null
      timeout_seconds: 3600
      retry_attempts: 3
      config:
        namespace: "rustci"
        service_account: "rustci-executor"

external_services:
  github:
    api_url: "https://api.github.com"
    timeout_seconds: 30
    retry_attempts: 3
    rate_limit_per_hour: 5000
  
  docker_registry:
    url: "https://registry-1.docker.io"
    username: null
    password: null
    timeout_seconds: 60
    insecure: false
  
  notification:
    enabled: false
    channels: []

features:
  enable_audit_logging: true
  enable_metrics_collection: true
  enable_distributed_tracing: false
  enable_hot_reload: true
  enable_experimental_features: false
  custom_flags: {}