name: "Build and Test"
description: "Build Rust application and run tests"
triggers:
  - trigger_type: manual
    config: {}
  - trigger_type: webhook
    config:
      events: ["push", "pull_request"]

stages:
  - name: "Build and Test"
    steps:
      - name: "fetch-dependencies"
        step_type: shell
        config:
          command: |
            cargo fetch
            
      - name: "check-formatting"
        step_type: shell
        config:
          command: |
            cargo fmt --check
            
      - name: "run-clippy"
        step_type: shell
        config:
          command: |
            cargo clippy -- -D warnings
            
      - name: "build-application"
        step_type: shell
        config:
          command: |
            cargo build --release
            
      - name: "run-unit-tests"
        step_type: shell
        config:
          command: |
            cargo test --lib
            
      - name: "run-integration-tests"
        step_type: shell
        config:
          command: |
            cargo test --test integration
            
      - name: "generate-test-coverage"
        step_type: shell
        config:
          command: |
            cargo tarpaulin --out xml --output-dir coverage/

environment:
  RUST_BACKTRACE: "1"
  CARGO_TERM_COLOR: "always"
timeout: 1200
retry_count: 1