name: "Docker Test App Deploy"
description: "Build and deploy test application using Docker"
triggers:
  - trigger_type: manual
    config: {}

stages:
  - name: "Build and Deploy"
    steps:
      - name: "build-docker-image"
        step_type: shell
        config:
          command: |
            cd test-app && \
            docker build -t rustci-test-app:latest .

      - name: "stop-existing-container"
        step_type: shell
        config:
          command: |
            docker rm -f rustci-test-container || true

      - name: "deploy-container"
        step_type: shell
        config:
          deployment_type: custom
          command: |
            docker run -d --name rustci-test-container -p 8080:8080 \
            -e RUST_LOG=info \
            -e PORT=8080 \
            rustci-test-app:latest

      - name: "verify-container"
        step_type: shell
        config:
          deployment_type: custom
          command: |
            sleep 10 && \
            docker ps | grep rustci-test-container && \
            curl -f http://localhost:8080/health

environment: {}
timeout: 1800
retry_count: 0
