# Valkyrie Protocol Standalone Configuration
# This configuration is optimized for production deployment

# Protocol Configuration
protocol:
  version: "2.0"
  max_connections: 1000000
  max_message_size: 67108864  # 64MB
  connection_timeout: "30s"
  keepalive_interval: "10s"
  enable_compression: true
  compression_algorithm: "lz4"

# Transport Configuration
transport:
  # TCP Transport
  tcp:
    enabled: true
    bind_address: "0.0.0.0:8080"
    nodelay: true
    keepalive: true
    keepalive_time: "7200s"
    keepalive_interval: "75s"
    keepalive_probes: 9
    recv_buffer_size: 65536
    send_buffer_size: 65536

  # QUIC Transport (HTTP/3)
  quic:
    enabled: true
    bind_address: "0.0.0.0:8443"
    max_streams: 1000
    max_stream_data: 1048576  # 1MB
    max_connection_data: 10485760  # 10MB
    idle_timeout: "30s"
    keep_alive_interval: "15s"

  # WebSocket Transport
  websocket:
    enabled: true
    path: "/ws"
    compression: true
    max_frame_size: 16777216  # 16MB
    max_message_size: 67108864  # 64MB
    ping_interval: "30s"
    pong_timeout: "10s"

  # Unix Socket Transport (disabled in container)
  unix:
    enabled: false

# Security Configuration
security:
  # TLS Configuration
  tls:
    enabled: true
    cert_file: "/etc/valkyrie/tls/tls.crt"
    key_file: "/etc/valkyrie/tls/tls.key"
    ca_file: "/etc/valkyrie/tls/ca.crt"
    min_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"
    verify_client_cert: false

  # Noise Protocol Configuration
  noise:
    enabled: true
    pattern: "XX"  # XX pattern for mutual authentication
    psk: ""  # Pre-shared key (empty = generate random)
    cipher: "ChaChaPoly"
    hash: "SHA256"
    dh: "25519"

  # Authentication Configuration
  auth:
    providers:
      - type: "jwt"
        config:
          issuer: "valkyrie-protocol"
          audience: "valkyrie-clients"
          algorithm: "RS256"
          public_key_file: "/etc/valkyrie/tls/jwt-public.pem"
          token_lifetime: "1h"
          refresh_lifetime: "24h"
      
      - type: "mtls"
        config:
          verify_client_cert: true
          ca_file: "/etc/valkyrie/tls/ca.crt"
          crl_file: "/etc/valkyrie/tls/crl.pem"
      
      - type: "api_key"
        config:
          header_name: "X-API-Key"
          query_param: "api_key"
          hash_algorithm: "sha256"

  # Authorization Configuration
  authz:
    enabled: true
    default_policy: "deny"
    policies:
      - name: "admin"
        rules:
          - resource: "*"
            action: "*"
            effect: "allow"
      - name: "user"
        rules:
          - resource: "jobs"
            action: ["create", "read", "update"]
            effect: "allow"
          - resource: "metrics"
            action: "read"
            effect: "allow"

# Performance Configuration
performance:
  # Runtime Configuration
  worker_threads: 0  # Auto-detect based on CPU cores
  max_blocking_threads: 512
  thread_stack_size: 2097152  # 2MB
  thread_name_prefix: "valkyrie"

  # Memory Configuration
  memory_pool_size: 1073741824  # 1GB
  enable_memory_pool: true
  gc_interval: "60s"

  # Optimization Flags
  enable_simd: true
  enable_zero_copy: true
  enable_vectored_io: true
  enable_splice: true  # Linux only
  enable_sendfile: true  # Linux only

  # Connection Pool Configuration
  connection_pool:
    max_idle_connections: 1000
    idle_timeout: "300s"
    max_lifetime: "3600s"

  # Buffer Configuration
  read_buffer_size: 65536
  write_buffer_size: 65536
  max_buffer_size: 1048576  # 1MB

# Streaming Configuration
streaming:
  # QoS Configuration
  qos:
    enabled: true
    default_priority: 100
    priority_levels:
      critical: 255
      high: 200
      normal: 100
      low: 50
      background: 10

  # Flow Control Configuration
  flow_control:
    enabled: true
    initial_window_size: 65536
    max_window_size: 16777216  # 16MB
    window_update_threshold: 0.5
    congestion_algorithm: "bbr"

  # Stream Multiplexing Configuration
  multiplexing:
    max_concurrent_streams: 1000
    stream_timeout: "300s"
    max_stream_buffer_size: 1048576  # 1MB

# Adapter Configuration
adapters:
  # HTTP Adapter
  http:
    enabled: true
    timeout: "30s"
    max_redirects: 3
    user_agent: "Valkyrie-Protocol/2.0"
    connection_pool_size: 100

  # Redis Adapter
  redis:
    enabled: false
    url: "redis://redis:6379"
    pool_size: 10
    timeout: "5s"
    retry_attempts: 3

  # NATS Adapter
  nats:
    enabled: false
    url: "nats://nats:4222"
    max_reconnects: 10
    reconnect_wait: "2s"

# Service Registry Configuration
registry:
  enabled: true
  backend: "memory"  # memory, etcd, consul, kubernetes
  health_check_interval: "30s"
  health_check_timeout: "10s"
  failure_threshold: 3
  recovery_threshold: 2

# Observability Configuration
observability:
  # Metrics Configuration
  metrics:
    enabled: true
    bind_address: "0.0.0.0:9090"
    path: "/metrics"
    update_interval: "15s"
    histogram_buckets: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0]

  # Tracing Configuration
  tracing:
    enabled: true
    jaeger_endpoint: "http://jaeger:14268/api/traces"
    sample_rate: 0.1
    max_tag_value_length: 1024
    batch_size: 100
    batch_timeout: "5s"

  # Logging Configuration
  logging:
    level: "info"
    format: "json"
    output: "stdout"
    max_size: "100MB"
    max_files: 10
    compress: true
    fields:
      service: "valkyrie-protocol"
      version: "2.0.0"

  # Health Check Configuration
  health:
    enabled: true
    bind_address: "0.0.0.0:8081"
    path: "/health"
    detailed_path: "/health/detailed"
    ready_path: "/health/ready"
    live_path: "/health/live"

# Feature Flags
features:
  experimental_quic: true
  experimental_rdma: false
  experimental_io_uring: false  # Linux only
  experimental_ebpf: false  # Linux only
  beta_http3: true
  beta_websocket_compression: true

# Development Configuration (disabled in production)
development:
  enabled: false
  debug_mode: false
  profile_mode: false
  trace_requests: false
  mock_adapters: false