# High-Performance Benchmark Configuration
# Optimized for maximum performance validation

benchmark_suite:
  name: "Valkyrie High-Performance Validation"
  version: "2.0"

http_bridge:
  concurrent_requests: 10000
  total_requests: 1000000
  payload_size: 512
  target_response_time_us: 100
  warmup_requests: 10000
  test_duration_seconds: 300

protocol_core:
  message_processing:
    message_sizes: [32, 64, 128, 256]
    target_throughput_msgs_per_sec: 10000000
  stream_multiplexing:
    concurrent_streams: [1000, 10000, 100000, 1000000]
    target_latency_us: 50

transport:
  quic:
    connection_counts: [1000, 10000, 100000, 1000000]
    target_latency_us: 100
    target_throughput_mbps: 50000
  unix_socket:
    connection_counts: [1000, 10000, 100000]
    target_latency_us: 50
    target_throughput_mbps: 100000
